### ISSUE TITLE
child is null

### ISSUE THREAD

**Issue by bensmeets** [davidworkman9/templating-ext#2]
Been trying to debug, but this is way out of my league. So just as a heads up, in my implementation the "findChildTemplate" call always returns null...

**Comment by bensmeets** [comment]
Could this be, because in my setup the "parent" is a child of someting else and/or wrapped by another component? a.k.a. the whole "with"-template wrapper issue.

**Comment by davidworkman9** [comment]
any chance you can give me some code that illustrates the issue?

**Comment by bensmeets** [comment]
Was struggling with meteorpad a bit, but I guess this one showes the issue. This one is without using wrappers, found I couldn't get it working without them either.

http://meteorpad.com/pad/juzxPeQeL37yhNb8J

**Comment by davidworkman9** [comment]
Sorry for the late reply, I definitely see the issue, working on a fix!

**Comment by emmanuelbuah** [comment]
This this issue still pending?

**Comment by davidworkman9** [comment]
@emmanuelbuah yes it is, in some cases it does work, others it doesn't.
